name: Release to production

on:
  release:
    types: [released]

jobs:
  build_linux:
    name: Build
    uses: ./.github/workflows/build_single_preset.yml
    with:
      godot-export-preset: linux
      file-extension: x86_64
      debug-mode: false

  build_mac:
    name: Build
    uses: ./.github/workflows/build_single_preset.yml
    with:
      godot-export-preset: mac
      file-extension: zip
      debug-mode: false

  build_web:
    name: Build
    uses: ./.github/workflows/build_single_preset.yml
    with:
      godot-export-preset: web
      file-extension: exe
      export-file-name: index
      debug-mode: false

  build_windows:
    name: Build
    uses: ./.github/workflows/build_single_preset.yml
    with:
      godot-export-preset: windows
      file-extension: zip
      debug-mode: false

  github_release_linux:
    needs: [build_linux]
    name: Append Linux artifact to GitHub release
    runs-on: ubuntu-latest

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ needs.build_linux.outputs.artifact-name }}

      - name: Add artifact to GitHub release
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ needs.build_linux.outputs.artifact-name }}.zip
          fail_on_unmatched_files: true

  github_release_mac:
    needs: [build_mac]
    name: Append macOS artifact to GitHub release
    runs-on: ubuntu-latest

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ needs.build_mac.outputs.artifact-name }}

      - name: Add artifact to GitHub release
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ needs.build_mac.outputs.artifact-name }}.zip
          fail_on_unmatched_files: true

  github_release_web:
    needs: [build_web]
    name: Append web artifact to GitHub release
    runs-on: ubuntu-latest

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ needs.build_web.outputs.artifact-name }}

      - name: Add artifact to GitHub release
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ needs.build_web.outputs.artifact-name }}.zip
          fail_on_unmatched_files: true

  github_release_windows:
    needs: [build_windows]
    name: Append Windows artifact to GitHub release
    runs-on: ubuntu-latest

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ needs.build_windows.outputs.artifact-name }}

      - name: Add artifact to GitHub release
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ needs.build_windows.outputs.artifact-name }}.zip
          fail_on_unmatched_files: true

  release_linux:
    needs: [build_linux, build_mac, build_web, build_windows]
    name: Release
    uses: ./.github/workflows/release_artifact.yml
    with:
      release-channel: linux-production
      artifact-name: ${{ needs.build_linux.outputs.artifact-name }}
    secrets: inherit

  release_mac:
    needs: [build_linux, build_mac, build_web, build_windows]
    name: Release
    uses: ./.github/workflows/release_artifact.yml
    with:
      release-channel: mac-production
      artifact-name: ${{ needs.build_mac.outputs.artifact-name }}
    secrets: inherit

  release_web:
    needs: [build_linux, build_mac, build_web, build_windows]
    name: Release
    uses: ./.github/workflows/release_artifact.yml
    with:
      release-channel: web-production
      artifact-name: ${{ needs.build_web.outputs.artifact-name }}
    secrets: inherit

  release_windows:
    needs: [build_linux, build_mac, build_web, build_windows]
    name: Release
    uses: ./.github/workflows/release_artifact.yml
    with:
      release-channel: windows-production
      artifact-name: ${{ needs.build_web.outputs.artifact-name }}
    secrets: inherit

  tag_commit:
    needs: [github_release_linux, github_release_mac, github_release_web, github_release_windows, release_linux, release_mac, release_web, release_windows]

    name: Create tag release-${{ github.run_number }}
    runs-on: ubuntu-latest

    steps:
      - name: Tag commit
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          custom_tag: release-${{ github.run_number }}
          tag_prefix: ""
